### ISSUE TITLE
If you have any questions, please write issues, and let me know.

### ISSUE THREAD

**Issue by keshikan** [keshikan/DSEG#1]

**Comment by mrthnmn** [comment]
Hello Keshikan,

I wanted to use your DSEG7 font for a code-camp project I am working on. The problem is, I am hosting the font file on my secure web site and apparently the font file gets the typeface from an unsecure Google site. This appears to be causing a CORS problem - many, if not all browsers now, will not allow secure sites to pull data from unsecure sites.

Do you know of any workarounds, short of editing the font file to route the request through a CORS proxy?

TIA,
Bruce Hyatt

**Comment by keshikan** [comment]
Hi Bruce,

Sorry, I have no idea about your problem.
I don't know a lot about CORS proxy.

keshikan

**Comment by mrthnmn** [comment]
I don't mean to suggest work for you but one solution might be to use https instead of http in the src urls (https://fonts.gstatic.com/s/lato/v13/UyBMtLsHKBKXelqf4x7VRQ.woff2). I checked and it appears to link to the same site this way.

Bruce

**Comment by keshikan** [comment]
Hi Bruce,
Thank you for informing me.

Umm.. is this a problem of DSEG font file itself? or SSL protocol? (or both?)

I just added [*.woff2](https://github.com/keshikan/DSEG/releases/tag/v0.42). I hope this release will solve your problem.

**Comment by mrthnmn** [comment]
Keshikan,

It turns out the problem is not with your file. I apologize. I thought it
was because the error I was getting indicated it was a cross-site access
problem which usually means you're trying to load something from an http
site into a https site.

Sincerely,
Bruce Hyatt
