### ISSUE TITLE
all-on character misaligns when adjusting spacing

### ISSUE THREAD

**Issue by SkyCharger001** [keshikan/DSEG#6]
in both openOffice and LibreOffice the following problem exists.
when tightening the spacing between characters (a technique I'd like to use to create the feel of a display that has jammed as many 14-segs per row as possible) the all-on symbol (which combined with a very dark shade I use to create the look of an all-dimmed 14SEG, but color is not the issue for this problem) gets misaligned in relation to the other characters.

I think this may be due to not adjusting the '~'s spacing data to match the rest.

**Comment by keshikan** [comment]
Hi, please tell me more details.
 
 * Font family name (DSEG14 Classic?)
 * How to reproduce the problem
 * Screenshot

I tried using "DSEG14 Classic-Italic" in LibreOffice5 Writer.
But I couldn't find any problems in case of tightening the spacing.
(See attachment)

![prob1](https://user-images.githubusercontent.com/16370619/30707298-088bbcbe-9f36-11e7-8cb3-ba879c596e49.PNG)

**Comment by SkyCharger001** [comment]
The issue isn't visible when using only one line
using DSEG14-modern-regular

![afbeelding](https://user-images.githubusercontent.com/22634314/30707734-b8893144-9efc-11e7-8de1-98b15d05d1fd.png)

Both lines **should** have the same length.

**Comment by keshikan** [comment]
I found the problems due to (may be) Office application.

When I changed font color, the spacing were changed too , and the problem you said were reproduced.
Moreover, when unifying color-settings, the problem were resolved.
(see attachment)

I think the problem is not caused by DSEG.

P.S.
DSEG series (including DSEG14 Modern-Regular) have monospaced glyphs except colon',' and space' ' character.

![prob2](https://user-images.githubusercontent.com/16370619/30769932-8cc1697e-a05e-11e7-962d-60c1aa78da37.PNG)

**Comment by SkyCharger001** [comment]
One of the key 'scenes' requires multiple shades of red to represent the uneven dimming and flickering of a device with low batteries, so that work-around is not an option for me.
So, for now at least, I'll keep the reduced spacing for just the depiction of the whole device (which only depicts its off-state and thus shows only inactive 14-seg units)
